# Fleet guardrails for the shipped Hermes agent (wsl orchestrator + domain-expert
# fleet), added after the 2026-09-10 live incident: the `photo-book-curator`
# expert ground for ~44 minutes on a live-Lightroom UI spot-check - a 5,016-line
# log, 25 window raises, 16 patch rounds on one helper - with no interim report.
# A first pass of guardrails then failed live: after the fleet was un-paused, the
# dispatcher reclaimed an orphaned card and the same expert drove the captain's
# LIVE Lightroom again, because (a) the rule only blocked live-app interaction
# *without an explicit task instruction* - and the orchestrator-authored card
# carried one, so the expert treated the card as authorization - and (b) the
# guardrails plugin was not present on experts created before it existed.
#
# This module is the SINGLE SOURCE OF TRUTH for the guardrail tunables. It:
#
#   1. declares `hermesGuardrails.*` options (overridable from
#      hosts/wsl/configuration.nix),
#   2. renders the orchestrator SOUL, the expert SOUL template and the shared
#      skills through those values, so the numbers in the prose come from the
#      options instead of being scattered magic numbers,
#   3. writes ~/.hermes/guardrails.yaml (the machine-readable copy the helper
#      CLIs and the `guardrails` plugin read), and
#   4. packages `hermes-guardrails` (print the tunables),
#      `hermes-desktop-lock` (the fleet-wide live-desktop lock), and
#      `hermes-live-app-authorize` (the captain-only per-task grant for
#      live-app control).
#
# The mechanical half is the `guardrails` Hermes plugin
# (modules/dev/hermes-plugins/guardrails): it default-denies every live-app
# control tool call unless the current task carries an unexpired CAPTAIN grant
# (the 2026-09-10 hole: an orchestrator card is not authorization), and it
# injects the fleet default `max_runtime_seconds` into every `kanban_create`
# that lacks one, so a card cannot be dispatched unbounded. The dispatcher then
# hard-stops the worker at the cap with a `timed_out` event.
#
# Scope: wsl only. The alps full brain (`modules/dev/joy-brain.nix`) keeps its
# own SOUL/skills and does not import this module.
{ config, lib, pkgs, ... }:
let
  hermesHome = "${config.home.homeDirectory}/.hermes";

  # The shared base skills live beside this module; their SKILL.md files are
  # rendered through the guardrail values below, and their scripts/ dirs are
  # copied through untouched.
  skillsSrc = ./hermes-skills;
  skillNames = builtins.attrNames
    (lib.filterAttrs (_: t: t == "directory") (builtins.readDir skillsSrc));

  # Escape the SOUL/skill placeholders that must survive to hermes-expert-new
  # (it stamps {{EXPERT_NAME}} / {{DOMAIN}} / {{DOMAIN_SCOPE}} at runtime).
  guardrailVars = {
    RUN_BUDGET_SECONDS = toString config.hermesGuardrails.runBudgetSeconds;
    RUN_BUDGET_MINUTES = toString (builtins.div config.hermesGuardrails.runBudgetSeconds 60);
    HEARTBEAT_SECONDS = toString config.hermesGuardrails.heartbeatSeconds;
    HEARTBEAT_MINUTES = toString (builtins.div config.hermesGuardrails.heartbeatSeconds 60);
    RETRY_BOUND = toString config.hermesGuardrails.retryBound;
    DESKTOP_LOCK_PATH = config.hermesGuardrails.desktopLockPath;
    DESKTOP_LOCK_TTL_SECONDS = toString config.hermesGuardrails.desktopLockTtlSeconds;
    DESKTOP_LOCK_TTL_MINUTES = toString (builtins.div config.hermesGuardrails.desktopLockTtlSeconds 60);
    DESKTOP_LOCK_WAIT_SECONDS = toString config.hermesGuardrails.desktopLockWaitSeconds;
    LIVE_APP_AUTH_DIR = config.hermesGuardrails.liveAppAuthDir;
    LIVE_APP_GRANT_TTL_MINUTES = toString (builtins.div config.hermesGuardrails.liveAppGrantTtlSeconds 60);
  };
  replaceGuardrailVars = lib.replaceStrings
    (map (name: "@${name}@") (builtins.attrNames guardrailVars))
    (builtins.attrValues guardrailVars);

  renderText = name: src: pkgs.writeText name (replaceGuardrailVars (builtins.readFile src));

  # Render one skill: SKILL.md through the guardrail values, scripts/ copied
  # as-is. `runCommand` (pure) keeps the per-skill derivation cacheable.
  renderSkill = name:
    let dir = skillsSrc + "/${name}";
    in pkgs.runCommand "hermes-skill-${name}-guardrails" { } (
      lib.concatStringsSep "\n" ([
        "mkdir -p $out"
        "cp ${renderText "SKILL.md" (dir + "/SKILL.md")} $out/SKILL.md"
      ] ++ lib.optional (builtins.pathExists (dir + "/scripts")) "cp -r ${dir}/scripts $out/scripts")
    );

  renderedSkills = pkgs.linkFarm "hermes-skills-guardrails"
    (map (name: { inherit name; path = renderSkill name; }) skillNames);

  guardrailsYaml = pkgs.writeText "hermes-guardrails.yaml" ''
    # Generated by modules/dev/hermes-guardrails.nix. Do not edit by hand;
    # override the hermesGuardrails.* options and re-run home-manager switch.
    schema: hermes-guardrails/v1
    run_budget_seconds: ${toString config.hermesGuardrails.runBudgetSeconds}
    heartbeat_seconds: ${toString config.hermesGuardrails.heartbeatSeconds}
    retry_bound: ${toString config.hermesGuardrails.retryBound}
    desktop_lock_path: "${config.hermesGuardrails.desktopLockPath}"
    desktop_lock_ttl_seconds: ${toString config.hermesGuardrails.desktopLockTtlSeconds}
    desktop_lock_wait_seconds: ${toString config.hermesGuardrails.desktopLockWaitSeconds}
    live_app_auth_dir: "${config.hermesGuardrails.liveAppAuthDir}"
    live_app_grant_ttl_seconds: ${toString config.hermesGuardrails.liveAppGrantTtlSeconds}
  '';

  hermesGuardrailsCli = pkgs.writeShellApplication {
    name = "hermes-guardrails";
    runtimeInputs = with pkgs; [ coreutils gnused gnugrep ];
    text = lib.replaceStrings [ "@HERMES_GUARDRAILS_HOME@" ]
      [ "${config.home.homeDirectory}/.hermes" ]
      (builtins.readFile ./hermes-guardrails-bin/hermes-guardrails);
  };

  hermesDesktopLock = pkgs.writeShellApplication {
    name = "hermes-desktop-lock";
    runtimeInputs = with pkgs; [ coreutils gnused gnugrep ];
    text = lib.replaceStrings [ "@HERMES_GUARDRAILS_HOME@" ]
      [ "${config.home.homeDirectory}/.hermes" ]
      (builtins.readFile ./hermes-guardrails-bin/hermes-desktop-lock);
  };

  # The CAPTAIN-only grant/revoke CLI for live-app control. The `guardrails`
  # plugin is default-deny; this is the one command that can lift that block,
  # and it is deliberately a captain tool, never something an agent runs.
  hermesLiveAppAuthorize = pkgs.writeShellApplication {
    name = "hermes-live-app-authorize";
    runtimeInputs = with pkgs; [ coreutils gnused gnugrep ];
    text = lib.replaceStrings [ "@HERMES_GUARDRAILS_HOME@" ]
      [ "${config.home.homeDirectory}/.hermes" ]
      (builtins.readFile ./hermes-guardrails-bin/hermes-live-app-authorize);
  };
in
{
  options.hermesGuardrails = {
    runBudgetSeconds = lib.mkOption {
      type = lib.types.ints.positive;
      default = 1800;
      example = 3600;
      description = ''
        Default per-task run budget in seconds. The orchestrator puts this on
        every card as `max_runtime_seconds`, and the `guardrails` plugin injects
        it into a `kanban_create` that omits the field. The kanban dispatcher
        hard-stops a worker at the cap (SIGTERM, then SIGKILL) and emits a
        `timed_out` event.
      '';
    };

    heartbeatSeconds = lib.mkOption {
      type = lib.types.ints.positive;
      default = 300;
      example = 600;
      description = ''
        Required progress-reporting cadence: an expert must post a durable
        `kanban_heartbeat`/`kanban_comment` at least this often. A run with no
        heartbeat beyond the interval is treated as a stall.
      '';
    };

    retryBound = lib.mkOption {
      type = lib.types.ints.positive;
      default = 3;
      example = 5;
      description = ''
        How many identical retries / re-patches of the same thing are allowed
        without measurable progress before the expert must hard-stop and report.
      '';
    };

    desktopLockTtlSeconds = lib.mkOption {
      type = lib.types.ints.positive;
      default = 1800;
      description = ''
        Time-to-live of the fleet-wide desktop lock. A long-lived UI session
        renews before this passes; a worker that dies without releasing the lock
        stops blocking the fleet once it expires.
      '';
    };

    desktopLockWaitSeconds = lib.mkOption {
      type = lib.types.ints.positive;
      default = 120;
      description = ''
        How long `hermes-desktop-lock acquire` waits for a busy lock before
        failing (a live-app card must be serialized fleet-wide, so waiting is
        normal; failing is how a wedged holder is surfaced).
      '';
    };

    desktopLockPath = lib.mkOption {
      type = lib.types.str;
      default = "${config.home.homeDirectory}/.hermes/run/desktop.lock";
      description = ''
        Path of the fleet-wide live-desktop lock. Shared by every expert profile
        because they all run as this same unix user; override only for a
        deliberately separate desktop.
      '';
    };

    liveAppAuthDir = lib.mkOption {
      type = lib.types.str;
      default = "${config.home.homeDirectory}/.hermes/live-app-authorization";
      description = ''
        Directory holding the captain's per-task live-app grants. The
        `guardrails` plugin resolves `<task>.grant` here and the
        `hermes-live-app-authorize` captain CLI writes it here. Shared by every
        profile because the plugin and the CLI both run as this unix user; the
        grants are per-task, not per-profile.
      '';
    };

    liveAppGrantTtlSeconds = lib.mkOption {
      type = lib.types.ints.positive;
      default = 7200;
      example = 3600;
      description = ''
        Default lifetime of a captain-issued live-app grant, in seconds. A grant
        is per-task and time-bounded so a forgotten authorization cannot cover
        later work; the captain can still override per grant with
        `hermes-live-app-authorize grant --minutes N`.
      '';
    };

    # Rendered artifacts consumed by modules/dev/hermes-home.nix and
    # modules/dev/hermes-skills.nix. Read-only: the module computes them from
    # the options above so the values in the prose cannot drift.
    soulFile = lib.mkOption {
      type = lib.types.path;
      readOnly = true;
      description = "Rendered orchestrator SOUL.md (guardrail values substituted).";
    };

    expertSoulTemplate = lib.mkOption {
      type = lib.types.path;
      readOnly = true;
      description = "Rendered domain-expert SOUL template (guardrail values substituted).";
    };

    skillsDir = lib.mkOption {
      type = lib.types.path;
      readOnly = true;
      description = "Rendered shared skills tree (guardrail values substituted).";
    };
  };

  config = {
    hermesGuardrails = {
      soulFile = renderText "hermes-orchestrator-SOUL.md" ./hermes-soul.md;
      expertSoulTemplate = renderText "hermes-domain-expert-SOUL.md" ./hermes-expert-soul.md;
      skillsDir = "${renderedSkills}";
    };

    # The helper CLIs are on PATH for the orchestrator, every expert worker, and
    # any interactive shell on this host.
    home.packages = [ hermesGuardrailsCli hermesDesktopLock hermesLiveAppAuthorize ];

    # ~/.hermes/guardrails.yaml: the machine-readable tunable copy the CLIs read,
    # plus the lock's parent dir. Runs after hermesHomeInstantiate (creates
    # ~/.hermes). The yaml is generated config, never rewritten by Hermes, so a
    # symlink to the store is safe.
    home.activation.hermesGuardrailsInstall =
      lib.hm.dag.entryAfter [ "hermesHomeInstantiate" ] ''
        _home=${lib.escapeShellArg hermesHome}
        $DRY_RUN_CMD mkdir -p "$_home/run"
        $DRY_RUN_CMD mkdir -p ${lib.escapeShellArg config.hermesGuardrails.liveAppAuthDir}
        $DRY_RUN_CMD ln -sfn ${lib.escapeShellArg "${guardrailsYaml}"} "$_home/guardrails.yaml"
      '';
  };
}
